# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-19 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='year',
            name='year',
            field=models.IntegerField(db_index=True, unique=True),
        ),
    ]
