# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-10 17:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fishing', '0002_auto_20160619_1244'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bigfish',
            options={'verbose_name': 'Fish', 'verbose_name_plural': 'Fish'},
        ),
    ]
