# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-31 21:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('link', models.CharField(max_length=64)),
                ('base_url', models.CharField(blank=True, max_length=100, null=True)),
                ('login_required', models.BooleanField(default=False)),
                ('anonymous_only', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubMenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('link', models.CharField(max_length=64)),
                ('base_url', models.CharField(blank=True, max_length=100, null=True)),
                ('login_required', models.BooleanField(default=False)),
                ('anonymous_only', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=10)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='navigation.MenuItem')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
