# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-31 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='order',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='submenuitem',
            name='order',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
