# Generated by Django 2.2 on 2020-07-22 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0002_auto_20200722_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientamount',
            name='order',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='step',
            name='order',
            field=models.IntegerField(default=5),
        ),
    ]
