# Generated by Django 2.2 on 2020-07-22 20:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0004_recipe_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 7, 22, 20, 15, 44, 599275, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
